language: rust
sudo: required
dist: trusty
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy-preview

script:
  - cargo clean
  - cargo clippy --all-features -- -D warnings
  - cargo build --all-features
  - cargo test --all-features

