[package]
name = "structopt-flags"
version = "0.1.0"
authors = ["Luca Pizzamiglio <luca.pizzamiglio@gmail.com>"]
readme = "README.md"
license = "BSD 3-Clause"
repository = "https://github.com/pizzamig/structopt-flags"

[badges]
travis-ci = { repository = "pizzamig/structopt-flags" }


[dependencies]
structopt = "0.2"
log = "0.4"

[dev-dependencies]
assert_cmd = "0.4"
failure = "*"
